### ISSUE TITLE
Cached documents get no updates from file changes in Nextcloud because the app Hooks does not work

### ISSUE THREAD

**Issue by andy-dots** [ONLYOFFICE/onlyoffice-nextcloud#562]
Nextcloud: 22.2.2
ONLYOFFICE App: 7.2.0
ONLYOFFICE Document Server: docker onlyoffice/documentserver:6.4.2.6

When open a document with ONLYOFFICE, this app creates a "key" and sends it to the ONLYOFFICE Document Server ("the etag to instruct ONLYOFFICE Document Server whether to download the document again or not").
After editing the document on the ONLYOFFICE Document Server and reopening it, the "key" has changed.
But when editing the document in Nextcloud by uploading a new version or editing and syncing it with a desktop clients, the "key" does not change. So opening the document with ONLYOFFICE shows still the last version edited by ONLYOFFICE and not the current one.
This is a serious bug because it overwrites the changes made without ONLYOFFICE.

I found out that the "fileUpdate" hook is not called when the document is changed by Nextcloud (["lib/hooks.php"](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/212be8a29299f7ed87a320fb5517874220e2de4d/lib/hooks.php#L48))
The Hooks::connectHooks() function gets called too late for that.
It is called in the "boot" function in ["appinfo/application.php"](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/212be8a29299f7ed87a320fb5517874220e2de4d/appinfo/application.php#L279)
But as you can see in the Nextcloud docs:
https://docs.nextcloud.com/server/latest/developer_manual/app_development/bootstrap.html#application-php
They use the "register" function for "registerEventListener".
I moved the "Hooks::connectHooks();" from "boot" to "register" and the "fileUpdate" hook is now called, when the document is changed by Nextcloud. So the document is called with a new "key" and ONLYOFFICE opens the current version.

**Comment by andy-dots** [comment]
This may although fix #405 because the "fileVersionRestore" hook is currently not called.

**Comment by colttt** [comment]
we hit the same issue, can you please post your diff/fixed files?

**Comment by andy-dots** [comment]
```diff
 appinfo/application.php | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/appinfo/application.php b/appinfo/application.php
index f96eee5..f1a9bb1 100644
--- a/appinfo/application.php
+++ b/appinfo/application.php
@@ -210,6 +210,7 @@ class Application extends App implements IBootstrap {
             $context->registerTemplateProvider(TemplateProvider::class);
         }
 
+        Hooks::connectHooks();
     }
 
     public function boot(IBootContext $context): void {
@@ -276,6 +277,5 @@ class Application extends App implements IBootstrap {
             });
         }
 
-        Hooks::connectHooks();
     }
 }
\ No newline at end of file
```

**Comment by biva** [comment]
Hello,

I think I meet this error as well but I'm not sure if it's the same. I use OnlyOffice 6.4.2 on Nextcloud 22. Sometimes, the version of the Excel file that is opened by OnlyOffice is not the same as the one on the server. What I see is:
1. My laptop is synced with Nextcloud, I open table.xlsx in Excel: this is the last version
2. Go to the Nextcloud WebUI, download table.xlsx and open it in Excel: this is the last version
3. Go to the Nextcloud WebUI and open table.xlsx in OnlyOffice: this is **not** the last version (even if I change the browser, clear cache, cookies, ...)

I'm not sure how to reproduce it, but here is my feeling:
1. Edit table.xlsx in OnlyOffice (online)
2. Close it
3. Sync Nextcloud desktop client 
4. Edit table.xlsx in Excel
5. Sync it
6. Open table.xlsx in OnlyOffice: the changes are not there

Is it the same? I reported it in https://github.com/nextcloud/documentserver_community/issues/248 but maybe I should close it?

**Comment by biva** [comment]
I tested the fix proposed in https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/566 and up to now it solves my problem, thank you so much and congrats!

**Comment by akitzing** [comment]
I tested the fix proposed in #566 and up to now it solves my problem, thank you so much !

**Comment by acsfer** [comment]
@LinneyS as this is a serious bug, couldn't a release be made as the fix has been merged?

**Comment by putt1ck** [comment]
For reference, this is highly reproducible:

create new document in NC, edit in OO;
close edit window;
download newly modified document (as a user pointed out, you might do this to work with it offline, or to do large scale changes e.g. to a spreadsheet that are easier done with desktop software);
edit the document;
upload it;
open it from NC in OO;
edits are not there.

**Comment by putt1ck** [comment]
NB confirm the fix fro #566 works, but does not resolve problems with edited documents uploaded prior to the patch
