### ISSUE TITLE
Cannot upgrade.

### ISSUE THREAD

**Issue by Vraiment** [ONLYOFFICE/onlyoffice-nextcloud#661]
When trying to upgrade my OnlyOffice installation and is failing with "Datbase error when running migration latest for app onlyoffice".

Looking at the logs the error says: `"An exception occurred while executing a query: SQLSTATE[42P07]: Duplicate table: 7 ERROR: the relationship «share_id_index» already exists"`

**Comment by jmcclelland** [comment]
I got the same error upgrading from 7.3.2 to 7.4.4. I'm using postgres - so I'm guessing this is an error that doesn't affect MySQL users. It seems like [this migration line](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/b057eed19335c128e87b1677bb0f942b8344fcc6/lib/Migration/Version070400Date20220607111111.php#L76) is relevant. I  think that the problem is that the name `share_id_index` [must be unique across the entire database in postgres, but not in MySQL](https://stackoverflow.com/questions/27306539/at-what-level-do-postgres-index-names-need-to-be-unique).

**Comment by jmcclelland** [comment]
Renaming the index works for me. I've submitted a PR to fix - not sure if that's the name you want to use or maybe there's an more elegant solution?

**Comment by Vraiment** [comment]
I solved my issue by removing the offending line instead of renaming it. If I recall correctly the index already exists for the same table.

**Comment by LinneyS** [comment]
Fixed at 3f043fb7772e8ba5efeae44e87cc3c7443fdb10b

**Comment by toxis** [comment]
> I solved my issue by removing the offending line instead of renaming it. If I recall correctly the index already exists for the same table.

Thanks! I solved this issue by commenting the line in /var/www/nextcloud/apps/onlyoffice/lib/Migration/Version070400Date20220607111111.php

`$table->addUniqueIndex(['share_id'], 'share_id_index');`

**Comment by Aincvy** [comment]
It still throws an error. It looks like `Version070400Date20220607111111.php` is always executed every time, and it interrupts the execution process. `Version070400Date20220929111111.php` is never executed.

P.S. My Nextcloud version is 30.0.4. Maybe this issue does not exist in newer versions.
