### ISSUE TITLE
forced session closing if 'auto_logout' is set

### ISSUE THREAD

**Issue by JojoBr0** [ONLYOFFICE/onlyoffice-nextcloud#673]
It seems like if you've activated the ['auto_logout' parameter](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#user-experience) (you have to scroll down to find it) in the nextcloud config.php file, the user gets logged out after the time even if you are editing meanwhile.

I've also found another comment regarding this behaviour: https://help.nextcloud.com/t/auto-logout-cannot-be-refreshed-when-using-onlyoffice/113160

**Comment by SergeyKorneyev** [comment]
Hello,
This should have been fixed in version 7.1 of the Document Server with the following commit: https://github.com/ONLYOFFICE/server/commit/0dc7ddc2ed73d717ae90c3f299b74473d16dfc9a.
Does the issue occur with the latest version for you?

**Comment by Hmmmz** [comment]
This is still a problem when I've tried but the "fix" might not be there anymore?

It looks like nextcloud's "auto_logout" function only adds window.addEventListener for "mousemove" and "touchstart" (also "storage" but that's for multiple tabs) and looks like that those don't trigger inside the iframe onlyoffice uses.

Link to nextcloud code that checks for user activity updates:
https://github.com/nextcloud/server/blob/v30.0.8/core/src/session-heartbeat.js#L93-L109

Is there maybe any new solution for this?
