### ISSUE TITLE
ERROR Onlyoffice not working with Nextcloud 25

### ISSUE THREAD

**Issue by andyxheli** [ONLYOFFICE/onlyoffice-nextcloud#690]
Currently there NC 25 beta 6 i installed onlyoffice app once i go info admin settings and click on onlyoffice i get this 

![image](https://user-images.githubusercontent.com/59488153/189439869-0bb8f91f-9943-4899-b141-857ef8153ca0.png)

{"reqId":"9oFojvdCeEkrK2yQIAHW","level":3,"time":"2022-09-09T20:41:41+00:00","remoteAddr":"10.0.10.90","user":"admin","app":"index","method":"GET","url":"/settings/admin/onlyoffice","message":"Class \"OCP\\App\" not found in file '/var/www/nextcloud/apps/onlyoffice/controller/settingscontroller.php' line 131","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","version":"25.0.0.11","exception":{"Exception":"Exception","Message":"Class \"OCP\\App\" not found in file '/var/www/nextcloud/apps/onlyoffice/controller/settingscontroller.php' line 131","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"Error","Message":"Class \"OCP\\App\" not found","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/onlyoffice/lib/adminsettings.php","line":43,"function":"index","class":"OCA\\Onlyoffice\\Controller\\SettingsController","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":129,"function":"getForm","class":"OCA\\Onlyoffice\\AdminSettings","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":145,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/onlyoffice/controller/settingscontroller.php","Line":131},"CustomMessage":"--"},"id":"631ba5882b3f5"}

**Comment by andyxheli** [comment]
@LinneyS is there anyone that can look into this

**Comment by lightweight** [comment]
Just upgraded to NC 25.0.0.18, and seeing this error, too.

**Comment by andyxheli** [comment]
fixed https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/tag/v7.6.6

**Comment by Bolli84** [comment]
On my instance, this issue still remains. The settings panel is not reachable, and by this the full onlyoffice-installation
